language: python
sudo: required
dist: xenial
python:
  - "2.7"
  - "3.7"
cache:
  pip: true
install:
  - pip install pytest
  - pip install mock
  - python setup.py develop
script:
  - py.test -vvs tests/
