language: python
sudo: required
dist: xenial
python:
  - "3.6"
  - "3.8"
cache:
  pip: true
install:
  - pip install pytest
  - pip install mock
  - python setup.py develop
script:
  - py.test -vvs tests/
