name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Run tests

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.6, 3.8]

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
    - name: Run tests
      run: |
        pytest